language: 
 - java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "tomaszuniek"
    token: dc71aec0900771bd51a26c0c50634ab69bfda8e9

install: 
 - true

script:
- mvn install
- mvn clean package sonar:sonar -Pcoverage -Dsonar.projectKey=Tomaszuniek_zadankodlakamila
- sonar-scanner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

