language: 
 - java

jdk:
  - openjdk8



deploy:
  provider: script
  script: "mvn test && mvn verify"
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
